# Generated by Django 4.2.6 on 2023-10-27 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="name",
        ),
        migrations.RemoveField(
            model_name="phonenumber",
            name="number",
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(default=1, max_length=100, verbose_name="Email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="firstname",
            field=models.CharField(default=1, max_length=100, verbose_name="Firstname"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="lastname",
            field=models.CharField(default=1, max_length=100, verbose_name="Lastname"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="mobile_phone",
            field=models.CharField(default=1, max_length=100, verbose_name="Mobile phone"),
            preserve_default=False,
        ),
    ]
